export type PlantStatus = "needs-water" | "healthy" | "quarantined" | "needs-mist";

export type Plant = {
  id: string;
  name: string;
  scientific: string;
  emoji: string;
  photo?: string;
  gradient: string;
  tone: string;
  status: PlantStatus;
  health: number;
  origin: string;
  toxicity: "Pet safe" | "Toxic to pets" | "Mildly toxic";
  water: string;
  // Approximate days between waterings, derived from `water`'s guidance —
  // drives the dashboard's watering calendar projection. Only set on
  // catalog plants that appear in the user's garden; falls back via
  // DEFAULT_WATER_INTERVAL_DAYS for the broader species catalog.
  waterIntervalDays?: number;
  sunlight: string;
  soil: string;
  fact: string;
  lastWatered: string;
  nextTask: string;
  timeline: TimelineEntry[];
};

export type TimelineChange = "improved" | "declined" | "stable" | "new";

export type TimelineEntry = {
  id: string;
  month: string; // e.g. "Mar 2026"
  date: string; // e.g. "March 12"
  emoji: string; // stand-in for uploaded photo
  gradient: string;
  health: number;
  change: TimelineChange;
  headline: string;
  detail: string;
  // True when a real photo was captured for this entry and saved in
  // IndexedDB (keyed by this entry's id) — see photoStore.ts. Older/seed
  // entries have no real photo, so the UI falls back to `emoji`.
  hasPhoto?: boolean;
  // Static seed-data image path (public/plants/*.jpg) — distinct from
  // `hasPhoto`, which points at a user-captured IndexedDB blob.
  photo?: string;
};

// All plants including the original demo + expanded catalog
const allDemoPlants: Plant[] = [
  {
    id: "monstera",
    name: "Monstera",
    scientific: "Monstera deliciosa",
    emoji: "🍃",
    photo: "/plants/monstera.jpg",
    gradient: "bg-[oklch(0.62_0.12_145)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "needs-water",
    health: 82,
    origin: "Southern Mexico & Panama",
    toxicity: "Toxic to pets",
    water:
      'Every 7–10 days. Let top 2" of soil dry out. Delayed by 2 days — humidity is 78% this week.',
    waterIntervalDays: 9,
    sunlight: "Bright, indirect light. Avoid direct afternoon sun.",
    soil: "Well-draining aroid mix with bark and perlite.",
    fact: "Its iconic leaf holes (fenestrations) evolved to let sunlight pass to lower leaves in the rainforest canopy.",
    lastWatered: "6 days ago",
    nextTask: "Water today",
    timeline: [
      {
        id: "m-1",
        month: "Nov 2025",
        date: "November 4",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 68,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline scan: 4 leaves, no fenestrations yet. AI set a 10-day watering rhythm.",
      },
      {
        id: "m-2",
        month: "Dec 2025",
        date: "December 6",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 74,
        change: "improved",
        headline: "First fenestration detected",
        detail:
          "Leaf 3 split along the midrib — a healthy sign of maturity in bright, indirect light.",
      },
      {
        id: "m-3",
        month: "Jan 2026",
        date: "January 9",
        emoji: "🍂",

        gradient: "bg-[oklch(0.85_0.05_140)]",
        health: 63,
        change: "declined",
        headline: "Mild yellowing on lower leaves",
        detail:
          "Likely overwatering during the cold snap. AI stretched the watering interval to 12 days.",
      },
      {
        id: "m-4",
        month: "Feb 2026",
        date: "February 10",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 78,
        change: "improved",
        headline: "Recovery underway",
        detail: "New growth point emerged. Yellowing halted after adjusted schedule.",
      },
      {
        id: "m-5",
        month: "Mar 2026",
        date: "March 12",
        emoji: "🌿",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 82,
        change: "stable",
        headline: "Two new leaves, both fenestrated",
        detail: "Humidity averaged 78% — AI delayed 2 waterings this month. Overall trend: steady.",
        hasPhoto: true,
      },
    ],
  },
  {
    id: "fiddle",
    name: "Fiddle Leaf Fig",
    scientific: "Ficus lyrata",
    emoji: "🌳",
    photo: "/plants/fiddle.jpg",
    gradient: "bg-[oklch(0.68_0.14_50)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 94,
    origin: "Western Africa",
    toxicity: "Toxic to pets",
    water: "Weekly. Consistency matters more than volume.",
    waterIntervalDays: 7,
    sunlight: "Very bright, indirect. Rotate weekly for even growth.",
    soil: "Rich, well-draining indoor potting mix.",
    fact: "Fiddle Leafs can grow 40 ft tall in the wild — indoors they cap out around 10 ft.",
    lastWatered: "2 days ago",
    nextTask: "Mist leaves",
    timeline: [
      {
        id: "f-1",
        month: "Dec 2025",
        date: "December 2",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 8 leaves, uniform color. Rotation reminder set for weekly.",
      },
      {
        id: "f-2",
        month: "Jan 2026",
        date: "January 5",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 86,
        change: "improved",
        headline: "Even growth, no leaf drop",
        detail: "Weekly rotation is paying off. Two new leaves this month.",
      },
      {
        id: "f-3",
        month: "Feb 2026",
        date: "February 8",
        emoji: "🍃",

        gradient: "bg-[oklch(0.85_0.05_140)]",
        health: 90,
        change: "improved",
        headline: "Glossy new foliage",
        detail: "Leaf color deepened — bright indirect light is dialed in.",
      },
      {
        id: "f-4",
        month: "Mar 2026",
        date: "March 10",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 94,
        change: "stable",
        headline: "Thriving",
        detail: "No stress markers detected. Continue current care.",
        hasPhoto: true,
      },
    ],
  },
  {
    id: "snake",
    name: "Snake Plant",
    scientific: "Dracaena trifasciata",
    emoji: "🗡️",
    photo: "/plants/snake.jpg",
    gradient: "bg-[oklch(0.58_0.1_155)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 99,
    origin: "West Africa",
    toxicity: "Mildly toxic",
    water: "Every 2–3 weeks. Drought tolerant — err on the dry side.",
    waterIntervalDays: 18,
    sunlight: "Anything from low light to bright indirect.",
    soil: "Fast-draining cactus/succulent mix.",
    fact: "NASA's clean-air study found it filters formaldehyde and benzene from indoor air.",
    lastWatered: "9 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "s-1",
        month: "Jan 2026",
        date: "January 14",
        emoji: "🪴",

        gradient: "bg-[oklch(0.86_0.05_45)]",
        health: 95,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 6 upright blades, firm to the touch.",
      },
      {
        id: "s-2",
        month: "Feb 2026",
        date: "February 15",
        emoji: "🪴",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 97,
        change: "stable",
        headline: "New pup at the base",
        detail: "First offset spotted — a sign the root system is happy.",
      },
      {
        id: "s-3",
        month: "Mar 2026",
        date: "March 15",
        emoji: "🪴",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 99,
        change: "improved",
        headline: "Effortless month",
        detail: "Watered twice. No change in color or firmness.",
        hasPhoto: true,
      },
    ],
  },
  {
    id: "pothos",
    name: "Golden Pothos",
    scientific: "Epipremnum aureum",
    emoji: "🌿",
    photo: "/plants/pothos.jpg",
    gradient: "bg-[oklch(0.78_0.13_95)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "needs-mist",
    health: 88,
    origin: "Solomon Islands",
    toxicity: "Toxic to pets",
    water: "When top inch feels dry, about every 7 days.",
    waterIntervalDays: 7,
    sunlight: "Low to bright indirect. Variegation deepens with more light.",
    soil: "Standard indoor mix with good drainage.",
    fact: "In tropical climates it can grow leaves up to 3 feet across.",
    lastWatered: "4 days ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "p-1",
        month: "Dec 2025",
        date: "December 18",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 76,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: two vines, minimal variegation.",
      },
      {
        id: "p-2",
        month: "Jan 2026",
        date: "January 20",
        emoji: "🍃",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 84,
        change: "improved",
        headline: "Variegation deepening",
        detail: "Moved closer to the window — new leaves show strong yellow marbling.",
      },
      {
        id: "p-3",
        month: "Feb 2026",
        date: "February 19",
        emoji: "🍃",

        gradient: "bg-[oklch(0.86_0.05_45)]",
        health: 88,
        change: "stable",
        headline: "Vines extended 12 cm",
        detail: "Growth pace matches expected spring pattern.",
        hasPhoto: true,
      },
    ],
  },
  {
    id: "calathea",
    name: "Calathea Orbifolia",
    scientific: "Goeppertia orbifolia",
    emoji: "🍂",
    photo: "/plants/calathea.jpg",
    gradient: "bg-[oklch(0.72_0.11_35)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "quarantined",
    health: 61,
    origin: "Bolivia",
    toxicity: "Pet safe",
    water: "Keep soil evenly moist. Filtered or rainwater only.",
    waterIntervalDays: 4,
    sunlight: "Medium, indirect. Direct sun scorches leaves.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Its leaves fold up at night — a movement called nyctinasty.",
    lastWatered: "1 day ago",
    nextTask: "Check for pests",
    timeline: [
      {
        id: "c-1",
        month: "Dec 2025",
        date: "December 22",
        emoji: "🌾",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 82,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 5 broad round leaves, silvery striping intact.",
      },
      {
        id: "c-2",
        month: "Jan 2026",
        date: "January 24",
        emoji: "🍂",

        gradient: "bg-[oklch(0.85_0.05_140)]",
        health: 70,
        change: "declined",
        headline: "Crispy edges appearing",
        detail: "Tap water suspected — AI switched recommendation to filtered water.",
      },
      {
        id: "c-3",
        month: "Feb 2026",
        date: "February 25",
        emoji: "🕷️",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 55,
        change: "declined",
        headline: "Spider mite webbing detected",
        detail: "Moved to quarantine. Neem oil treatment scheduled every 5 days.",
      },
      {
        id: "c-4",
        month: "Mar 2026",
        date: "March 26",
        emoji: "🌾",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 61,
        change: "improved",
        headline: "Infestation contained",
        detail: "No new webbing in 10 days. Two unfurling leaves — early recovery signs.",
        hasPhoto: true,
      },
    ],
  },
];

// Broader species catalog for AI-scan matching only
const catalogPlants: Plant[] = [
  {
    id: "zz-plant",
    name: "ZZ Plant",
    scientific: "Zamioculcas zamiifolia",
    emoji: "🪴",
    photo: "/plants/zz-plant.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 90,
    origin: "Eastern Africa",
    toxicity: "Toxic to pets",
    water: "Every 2–3 weeks. Extremely drought tolerant.",
    sunlight: "Low to bright indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Stores water in thick rhizomes, letting it survive months of neglect.",
    lastWatered: "12 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "zz-1",
        month: "Feb 2026",
        date: "February 3",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 84,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 5 glossy stalks, no damage.",
      },
      {
        id: "zz-2",
        month: "Mar 2026",
        date: "March 5",
        emoji: "🪴",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 90,
        change: "improved",
        headline: "New stalk emerging",
        detail: "A fresh rhizome shoot broke soil — sign of a happy root system.",
      },
    ],
  },
  {
    id: "peace-lily",
    name: "Peace Lily",
    scientific: "Spathiphyllum wallisii",
    emoji: "🌸",
    photo: "/plants/peace-lily.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 85,
    origin: "Tropical Americas",
    toxicity: "Toxic to pets",
    water: "Weekly — droops noticeably when thirsty, recovers fast after watering.",
    sunlight: "Low to medium indirect light.",
    soil: "Rich, moisture-retentive potting mix.",
    fact: "Its white 'flower' is actually a modified leaf called a spathe.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pl-1",
        month: "Jan 2026",
        date: "January 18",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 78,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 6 leaves, one spathe forming.",
      },
      {
        id: "pl-2",
        month: "Feb 2026",
        date: "February 20",
        emoji: "🌸",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 85,
        change: "improved",
        headline: "First bloom opened",
        detail: "Spathe fully unfurled — bright white against dark green leaves.",
      },
    ],
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    scientific: "Aloe vera",
    emoji: "🌵",
    photo: "/plants/aloe-vera.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 93,
    origin: "Arabian Peninsula",
    toxicity: "Mildly toxic",
    water: "Every 3 weeks. Let soil dry completely between waterings.",
    sunlight: "Bright, direct to indirect light.",
    soil: "Fast-draining cactus/succulent mix.",
    fact: "The gel inside its leaves has been used topically for burns for centuries.",
    lastWatered: "10 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "av-1",
        month: "Feb 2026",
        date: "February 8",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 88,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 7 firm, plump leaves.",
      },
      {
        id: "av-2",
        month: "Mar 2026",
        date: "March 10",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 93,
        change: "improved",
        headline: "New pup at base",
        detail: "A small offset appeared — healthy root expansion.",
      },
    ],
  },
  {
    id: "spider-plant",
    name: "Spider Plant",
    scientific: "Chlorophytum comosum",
    emoji: "🕸️",
    photo: "/plants/spider-plant.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 91,
    origin: "South Africa",
    toxicity: "Pet safe",
    water: "Weekly, keep lightly moist.",
    sunlight: "Bright, indirect light.",
    soil: "Standard well-draining potting mix.",
    fact: "Produces plantlets on long stems that can be rooted into new plants.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sp-1",
        month: "Jan 2026",
        date: "January 22",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 82,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: dense rosette, no plantlets yet.",
      },
      {
        id: "sp-2",
        month: "Feb 2026",
        date: "February 24",
        emoji: "🕸️",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 91,
        change: "improved",
        headline: "First plantlets forming",
        detail: "Two baby spiders dangling from runners — ready to propagate.",
      },
    ],
  },
  {
    id: "philodendron-brasil",
    name: "Philodendron Brasil",
    scientific: "Philodendron hederaceum 'Brasil'",
    emoji: "🌿",
    photo: "/plants/philodendron-brasil.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 87,
    origin: "Central & South America",
    toxicity: "Toxic to pets",
    water: "Weekly, when top inch is dry.",
    sunlight: "Bright, indirect. More light deepens variegation.",
    soil: "Well-draining aroid mix.",
    fact: "Its lime-and-green variegation follows a genetic stripe pattern unique to each leaf.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pb-1",
        month: "Feb 2026",
        date: "February 12",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: trailing vine, 10 leaves.",
      },
      {
        id: "pb-2",
        month: "Mar 2026",
        date: "March 14",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 87,
        change: "improved",
        headline: "Vine extended",
        detail: "New growth shows strong yellow-green variegation.",
      },
    ],
  },
  {
    id: "rubber-plant",
    name: "Rubber Plant",
    scientific: "Ficus elastica",
    emoji: "🍃",
    photo: "/plants/rubber-plant.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 89,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Every 7–10 days.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Historically tapped for natural latex before Brazilian rubber trees took over production.",
    lastWatered: "6 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "rp-1",
        month: "Jan 2026",
        date: "January 27",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 82,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 9 dark glossy leaves.",
      },
      {
        id: "rp-2",
        month: "Feb 2026",
        date: "February 28",
        emoji: "🍃",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 89,
        change: "improved",
        headline: "New leaf unfurled",
        detail: "Fresh burgundy sheath dropped, revealing a healthy new leaf.",
      },
    ],
  },
  {
    id: "jade-plant",
    name: "Jade Plant",
    scientific: "Crassula ovata",
    emoji: "🍀",
    photo: "/plants/jade-plant.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 95,
    origin: "South Africa",
    toxicity: "Toxic to pets",
    water: "Every 2–3 weeks. Drought tolerant.",
    sunlight: "Bright, direct to indirect light.",
    soil: "Fast-draining succulent mix.",
    fact: "Considered a symbol of good luck and prosperity in many cultures.",
    lastWatered: "11 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "jp-1",
        month: "Feb 2026",
        date: "February 5",
        emoji: "🍀",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 90,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: thick woody stem, plump leaves.",
      },
      {
        id: "jp-2",
        month: "Mar 2026",
        date: "March 7",
        emoji: "🍀",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 95,
        change: "improved",
        headline: "New branch forming",
        detail: "Compact new growth at the stem tip — classic jade shape.",
      },
    ],
  },
  {
    id: "orchid",
    name: "Phalaenopsis Orchid",
    scientific: "Phalaenopsis amabilis",
    emoji: "🌺",
    photo: "/plants/orchid.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 80,
    origin: "Southeast Asia",
    toxicity: "Pet safe",
    water: "Weekly ice-cube method or soak-and-drain.",
    sunlight: "Bright, indirect light. No direct sun.",
    soil: "Chunky bark-based orchid mix, not regular soil.",
    fact: "Roots photosynthesize and turn green when watered, silvery-grey when dry.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "or-1",
        month: "Jan 2026",
        date: "January 30",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 72,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: one spike, buds not yet open.",
      },
      {
        id: "or-2",
        month: "Mar 2026",
        date: "March 2",
        emoji: "🌺",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 80,
        change: "improved",
        headline: "Blooms opened",
        detail: "Four flowers fully open along the spike.",
      },
    ],
  },
  {
    id: "peperomia",
    name: "Peperomia",
    scientific: "Peperomia obtusifolia",
    emoji: "🌿",
    photo: "/plants/peperomia.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 88,
    origin: "Tropical Americas",
    toxicity: "Pet safe",
    water: "Every 10 days. Let soil dry between waterings.",
    sunlight: "Medium to bright indirect light.",
    soil: "Light, well-draining potting mix.",
    fact: "Thick, succulent-like leaves store water, making it forgiving of missed waterings.",
    lastWatered: "7 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pe-1",
        month: "Feb 2026",
        date: "February 14",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 83,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: compact rounded leaves, glossy.",
      },
      {
        id: "pe-2",
        month: "Mar 2026",
        date: "March 16",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 88,
        change: "improved",
        headline: "Bushier growth",
        detail: "Several new leaf pairs — healthy, compact growth habit.",
      },
    ],
  },
  {
    id: "boston-fern",
    name: "Boston Fern",
    scientific: "Nephrolepis exaltata",
    emoji: "🌿",
    photo: "/plants/boston-fern.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 76,
    origin: "Tropical Americas",
    toxicity: "Pet safe",
    water: "Every 3–4 days. Keep consistently moist, high humidity.",
    sunlight: "Medium, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "One of the most effective houseplants for adding humidity to a room.",
    lastWatered: "2 days ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "bf-1",
        month: "Feb 2026",
        date: "February 9",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 70,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: fronds slightly sparse from transport stress.",
      },
      {
        id: "bf-2",
        month: "Mar 2026",
        date: "March 11",
        emoji: "🌿",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 76,
        change: "improved",
        headline: "New fronds unfurling",
        detail: "Increased misting schedule is paying off — fuller growth.",
      },
    ],
  },
  {
    id: "english-ivy",
    name: "English Ivy",
    scientific: "Hedera helix",
    emoji: "🍃",
    photo: "/plants/english-ivy.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 84,
    origin: "Europe & Western Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, keep soil evenly moist.",
    sunlight: "Medium to bright indirect light.",
    soil: "Standard well-draining potting mix.",
    fact: "A vigorous climber that can attach to surfaces using tiny root-like structures.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ei-1",
        month: "Feb 2026",
        date: "February 16",
        emoji: "🍃",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 79,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: trailing vines, dense small leaves.",
      },
      {
        id: "ei-2",
        month: "Mar 2026",
        date: "March 18",
        emoji: "🍃",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 84,
        change: "improved",
        headline: "Vines extended",
        detail: "Noticeable new growth along all trailing stems.",
      },
    ],
  },
  {
    id: "chinese-money-plant",
    name: "Chinese Money Plant",
    scientific: "Pilea peperomioides",
    emoji: "🪙",

    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 86,
    origin: "Southern China",
    toxicity: "Pet safe",
    water: "Weekly, let top inch dry.",
    sunlight: "Bright, indirect light. Rotate for even growth.",
    soil: "Well-draining potting mix.",
    fact: "Its round, coin-shaped leaves have made it a popular plant to share as cuttings.",
    lastWatered: "4 days ago",
    nextTask: "Rotate for even growth",
    timeline: [
      {
        id: "cm-1",
        month: "Feb 2026",
        date: "February 19",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 8 round leaves on thin stems.",
      },
      {
        id: "cm-2",
        month: "Mar 2026",
        date: "March 21",
        emoji: "🪙",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 86,
        change: "improved",
        headline: "Pups sprouting",
        detail: "Two baby plants emerging from the base.",
      },
    ],
  },
  {
    id: "string-of-pearls",
    name: "String of Pearls",
    scientific: "Curio rowleyanus",
    emoji: "📿",
    photo: "/plants/string-of-pearls.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 79,
    origin: "Southwest Africa",
    toxicity: "Toxic to pets",
    water: "Every 2 weeks. Very drought tolerant.",
    sunlight: "Bright, indirect to direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Each bead-like leaf is a water-storing sphere with a translucent stripe for light capture.",
    lastWatered: "9 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sop-1",
        month: "Feb 2026",
        date: "February 22",
        emoji: "📿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 74,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: trailing strands, plump beads.",
      },
      {
        id: "sop-2",
        month: "Mar 2026",
        date: "March 24",
        emoji: "📿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 79,
        change: "improved",
        headline: "New strands trailing",
        detail: "Several new bead chains extending over the pot edge.",
      },
    ],
  },
  {
    id: "bird-of-paradise",
    name: "Bird of Paradise",
    scientific: "Strelitzia nicolai",
    emoji: "🦅",
    photo: "/plants/bird-of-paradise.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 88,
    origin: "South Africa",
    toxicity: "Mildly toxic",
    water: "Weekly, keep soil consistently moist.",
    sunlight: "Bright, direct to indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Named for its exotic flowers resembling a bird's crest, rare in indoor conditions.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "bp-1",
        month: "Jan 2026",
        date: "January 25",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 81,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 5 large paddle leaves.",
      },
      {
        id: "bp-2",
        month: "Mar 2026",
        date: "March 1",
        emoji: "🦅",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 88,
        change: "improved",
        headline: "New leaf split",
        detail: "Latest leaf naturally split along its ribs — a maturity sign.",
      },
    ],
  },
  {
    id: "areca-palm",
    name: "Areca Palm",
    scientific: "Dypsis lutescens",
    emoji: "🌴",
    photo: "/plants/areca-palm.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 83,
    origin: "Madagascar",
    toxicity: "Pet safe",
    water: "Weekly, keep lightly moist.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "One of the top air-purifying plants identified in NASA's clean air study.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ap-1",
        month: "Feb 2026",
        date: "February 11",
        emoji: "🌴",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 78,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 4 feathery fronds.",
      },
      {
        id: "ap-2",
        month: "Mar 2026",
        date: "March 13",
        emoji: "🌴",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 83,
        change: "improved",
        headline: "New frond unfurled",
        detail: "Fresh frond fully opened, deep green color.",
      },
    ],
  },
  {
    id: "croton",
    name: "Croton",
    scientific: "Codiaeum variegatum",
    emoji: "🍂",
    photo: "/plants/croton.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 81,
    origin: "Southeast Asia & Pacific Islands",
    toxicity: "Toxic to pets",
    water: "Weekly, keep soil evenly moist.",
    sunlight: "Bright, direct light for best color.",
    soil: "Rich, well-draining potting mix.",
    fact: "Leaf color intensity is directly tied to how much bright light it receives.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "cr-1",
        month: "Feb 2026",
        date: "February 17",
        emoji: "🍂",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 75,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: mixed red-yellow-green leaves.",
      },
      {
        id: "cr-2",
        month: "Mar 2026",
        date: "March 19",
        emoji: "🍂",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 81,
        change: "improved",
        headline: "Color deepened",
        detail: "New leaves show more vivid red and orange after move to brighter spot.",
      },
    ],
  },
  {
    id: "anthurium",
    name: "Anthurium",
    scientific: "Anthurium andraeanum",
    emoji: "❤️",
    photo: "/plants/anthurium.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 86,
    origin: "Colombia & Ecuador",
    toxicity: "Toxic to pets",
    water: "Weekly, let top inch dry.",
    sunlight: "Bright, indirect light.",
    soil: "Chunky, well-draining aroid mix.",
    fact: "Its glossy heart-shaped 'flower' is a waxy spathe, with the true flowers on the central spike.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "an-1",
        month: "Feb 2026",
        date: "February 21",
        emoji: "❤️",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: two blooms, glossy foliage.",
      },
      {
        id: "an-2",
        month: "Mar 2026",
        date: "March 23",
        emoji: "❤️",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 86,
        change: "improved",
        headline: "New bloom opening",
        detail: "A third spathe unfurling — consistent bloom cycle.",
      },
    ],
  },
  {
    id: "dracaena-marginata",
    name: "Dragon Tree",
    scientific: "Dracaena marginata",
    emoji: "🌴",
    photo: "/plants/dracaena-marginata.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 90,
    origin: "Madagascar",
    toxicity: "Toxic to pets",
    water: "Every 2 weeks. Drought tolerant.",
    sunlight: "Bright to medium indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Thin, red-edged leaves radiate from the top of narrow, sculptural stems.",
    lastWatered: "8 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "dm-1",
        month: "Feb 2026",
        date: "February 6",
        emoji: "🌴",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 85,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: single cane, spiky rosette.",
      },
      {
        id: "dm-2",
        month: "Mar 2026",
        date: "March 8",
        emoji: "🌴",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 90,
        change: "improved",
        headline: "New growth point",
        detail: "A second growth point split at the crown.",
      },
    ],
  },
  {
    id: "haworthia",
    name: "Haworthia",
    scientific: "Haworthiopsis attenuata",
    emoji: "🌵",
    photo: "/plants/haworthia.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 92,
    origin: "South Africa",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Let soil dry fully.",
    sunlight: "Bright, indirect light.",
    soil: "Fast-draining cactus/succulent mix.",
    fact: "Small enough for windowsills, its white bumpy stripes mimic natural camouflage.",
    lastWatered: "13 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "hw-1",
        month: "Feb 2026",
        date: "February 25",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 87,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: tight rosette, firm leaves.",
      },
      {
        id: "hw-2",
        month: "Mar 2026",
        date: "March 27",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 92,
        change: "improved",
        headline: "New offset",
        detail: "Small pup emerged at the base of the rosette.",
      },
    ],
  },
  {
    id: "christmas-cactus",
    name: "Christmas Cactus",
    scientific: "Schlumbergera bridgesii",
    emoji: "🌸",
    photo: "/plants/christmas-cactus.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 84,
    origin: "Brazil",
    toxicity: "Pet safe",
    water: "Weekly, keep lightly moist during bloom season.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining potting mix with added organic matter.",
    fact: "Unlike desert cacti, it's a tropical rainforest epiphyte and prefers humidity.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "cc-1",
        month: "Feb 2026",
        date: "February 13",
        emoji: "🌱",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 78,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: segmented stems, no buds yet.",
      },
      {
        id: "cc-2",
        month: "Mar 2026",
        date: "March 15",
        emoji: "🌸",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 84,
        change: "improved",
        headline: "Buds opening",
        detail: "First blooms of the season opened at stem tips.",
      },
    ],
  },
  {
    id: "air-plant",
    name: "Air Plant",
    scientific: "Tillandsia ionantha",
    emoji: "🌾",
    photo: "/plants/air-plant.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 82,
    origin: "Central America",
    toxicity: "Pet safe",
    water: "Soak or mist 2–3 times weekly. No soil.",
    sunlight: "Bright, indirect light.",
    soil: "None — grows without soil, mounted or displayed freely.",
    fact: "Absorbs water and nutrients through specialized leaf scales called trichomes.",
    lastWatered: "2 days ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "airp-1",
        month: "Feb 2026",
        date: "February 27",
        emoji: "🌾",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 77,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: silvery-green leaves, tight rosette.",
      },
      {
        id: "airp-2",
        month: "Mar 2026",
        date: "March 29",
        emoji: "🌾",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 82,
        change: "improved",
        headline: "Blush developing",
        detail: "Center leaves turning pink-red — a sign it may bloom soon.",
      },
    ],
  },
  {
    id: "bromeliad",
    name: "Bromeliad",
    scientific: "Guzmania lingulata",
    emoji: "🌺",
    photo: "/plants/bromeliad.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 85,
    origin: "Central & South America",
    toxicity: "Pet safe",
    water: "Keep central cup filled with water, mist weekly.",
    sunlight: "Bright, indirect light.",
    soil: "Loose, well-draining epiphyte mix.",
    fact: "The colorful central bracts last for months, far longer than typical flowers.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "br-1",
        month: "Feb 2026",
        date: "February 4",
        emoji: "🌺",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: bright red central bract, glossy leaves.",
      },
      {
        id: "br-2",
        month: "Mar 2026",
        date: "March 6",
        emoji: "🌺",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 85,
        change: "stable",
        headline: "Bract still vivid",
        detail: "No fading — central cup consistently topped up.",
      },
    ],
  },
  {
    id: "begonia",
    name: "Begonia",
    scientific: "Begonia rex",
    emoji: "🍁",
    photo: "/plants/begonia.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 77,
    origin: "Tropical & subtropical regions",
    toxicity: "Toxic to pets",
    water: "Weekly, avoid wetting leaves.",
    sunlight: "Medium, indirect light.",
    soil: "Light, well-draining potting mix.",
    fact: "Grown mainly for its dramatic swirling leaf patterns rather than its flowers.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "bg-1",
        month: "Feb 2026",
        date: "February 15",
        emoji: "🍁",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 71,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: patterned leaves, slight edge curling.",
      },
      {
        id: "bg-2",
        month: "Mar 2026",
        date: "March 17",
        emoji: "🍁",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 77,
        change: "improved",
        headline: "Curling resolved",
        detail: "Raised humidity stopped leaf-edge curling — new growth is flat and vivid.",
      },
    ],
  },
  {
    id: "african-violet",
    name: "African Violet",
    scientific: "Saintpaulia ionantha",
    emoji: "💜",
    photo: "/plants/african-violet.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 80,
    origin: "Tanzania & Kenya",
    toxicity: "Pet safe",
    water: "Weekly, bottom-water to avoid leaf spotting.",
    sunlight: "Bright, indirect light.",
    soil: "Light, well-draining African violet mix.",
    fact: "Fuzzy leaves are sensitive to cold water spots, which can cause permanent marks.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "avi-1",
        month: "Feb 2026",
        date: "February 23",
        emoji: "💜",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 74,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: fuzzy leaves, one flower stalk.",
      },
      {
        id: "avi-2",
        month: "Mar 2026",
        date: "March 25",
        emoji: "💜",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 80,
        change: "improved",
        headline: "More blooms",
        detail: "Two additional flower stalks since switching to bottom-watering.",
      },
    ],
  },
  {
    id: "money-tree",
    name: "Money Tree",
    scientific: "Pachira aquatica",
    emoji: "🌳",
    photo: "/plants/money-tree.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 87,
    origin: "Central & South America",
    toxicity: "Pet safe",
    water: "Every 1–2 weeks, let top dry.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Often sold with braided trunks, a technique that doesn't harm the plant.",
    lastWatered: "6 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "mt-1",
        month: "Jan 2026",
        date: "January 29",
        emoji: "🌳",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 82,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: braided trunk, 5-leaf clusters.",
      },
      {
        id: "mt-2",
        month: "Mar 2026",
        date: "March 3",
        emoji: "🌳",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 87,
        change: "improved",
        headline: "New leaf cluster",
        detail: "A fresh 5-leaf cluster opened at the crown.",
      },
    ],
  },
  {
    id: "prayer-plant",
    name: "Prayer Plant",
    scientific: "Maranta leuconeura",
    emoji: "🌿",
    photo: "/plants/prayer-plant.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 75,
    origin: "Brazil",
    toxicity: "Pet safe",
    water: "Keep soil evenly moist, filtered water preferred.",
    sunlight: "Medium, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Leaves fold upright at night, like praying hands — hence the name.",
    lastWatered: "1 day ago",
    nextTask: "Check for pests",
    timeline: [
      {
        id: "pr-1",
        month: "Feb 2026",
        date: "February 18",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 70,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: red-veined leaves, minor curling.",
      },
      {
        id: "pr-2",
        month: "Mar 2026",
        date: "March 20",
        emoji: "🌿",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 75,
        change: "improved",
        headline: "Curling reduced",
        detail: "Switch to filtered water reduced leaf-edge browning.",
      },
    ],
  },
  {
    id: "asparagus-fern",
    name: "Asparagus Fern",
    scientific: "Asparagus setaceus",
    emoji: "🌿",
    photo: "/plants/asparagus-fern.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 79,
    origin: "Southern Africa",
    toxicity: "Toxic to pets",
    water: "Weekly, keep evenly moist.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Not a true fern — it's related to asparagus, with feathery needle-like foliage.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "af-1",
        month: "Feb 2026",
        date: "February 26",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 73,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: feathery fronds, light shedding from transport.",
      },
      {
        id: "af-2",
        month: "Mar 2026",
        date: "March 28",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 79,
        change: "improved",
        headline: "New fronds filling in",
        detail: "Shedding stopped, fresh feathery growth throughout.",
      },
    ],
  },
  {
    id: "cast-iron-plant",
    name: "Cast Iron Plant",
    scientific: "Aspidistra elatior",
    emoji: "🌿",
    photo: "/plants/cast-iron-plant.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 96,
    origin: "Japan & Taiwan",
    toxicity: "Pet safe",
    water: "Every 2 weeks. Extremely tolerant of neglect.",
    sunlight: "Low to medium indirect light.",
    soil: "Standard well-draining potting mix.",
    fact: "Named for its ability to survive poor light, drought, and neglect better than almost any houseplant.",
    lastWatered: "10 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "cip-1",
        month: "Jan 2026",
        date: "January 31",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 93,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: broad dark-green leaves, no damage.",
      },
      {
        id: "cip-2",
        month: "Mar 2026",
        date: "March 4",
        emoji: "🌿",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 96,
        change: "stable",
        headline: "No change needed",
        detail: "Thrives with minimal care — no visible stress markers.",
      },
    ],
  },
  {
    id: "chinese-evergreen",
    name: "Chinese Evergreen",
    scientific: "Aglaonema commutatum",
    emoji: "🌿",
    photo: "/plants/chinese-evergreen.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 83,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, let top inch dry.",
    sunlight: "Low to medium indirect light.",
    soil: "Well-draining potting mix.",
    fact: "One of the most tolerant houseplants of low light and fluctuating humidity.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ce-1",
        month: "Feb 2026",
        date: "February 7",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 78,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: silver-green mottled leaves.",
      },
      {
        id: "ce-2",
        month: "Mar 2026",
        date: "March 9",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 83,
        change: "improved",
        headline: "New leaf emerging",
        detail: "Fresh mottled leaf unfurling at the crown.",
      },
    ],
  },
  {
    id: "kalanchoe",
    name: "Kalanchoe",
    scientific: "Kalanchoe blossfeldiana",
    emoji: "🌷",
    photo: "/plants/kalanchoe.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 81,
    origin: "Madagascar",
    toxicity: "Toxic to pets",
    water: "Every 2 weeks. Let soil dry between waterings.",
    sunlight: "Bright, direct to indirect light.",
    soil: "Fast-draining succulent mix.",
    fact: "Clusters of tiny flowers can stay in bloom for several weeks at a time.",
    lastWatered: "8 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ka-1",
        month: "Feb 2026",
        date: "February 10",
        emoji: "🌷",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 75,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: buds tight, not yet open.",
      },
      {
        id: "ka-2",
        month: "Mar 2026",
        date: "March 12",
        emoji: "🌷",

        gradient: "bg-[oklch(0.86_0.03_60)]",
        health: 81,
        change: "improved",
        headline: "Full bloom",
        detail: "Clusters of small flowers opened across the plant.",
      },
    ],
  },
  {
    id: "ponytail-palm",
    name: "Ponytail Palm",
    scientific: "Beaucarnea recurvata",
    emoji: "🌴",
    photo: "/plants/ponytail-palm.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 94,
    origin: "Eastern Mexico",
    toxicity: "Pet safe",
    water: "Every 3–4 weeks. Bulbous base stores water.",
    sunlight: "Bright, direct to indirect light.",
    soil: "Fast-draining cactus/succulent mix.",
    fact: "Not a true palm — it's a succulent with a swollen water-storing trunk base.",
    lastWatered: "14 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pp-1",
        month: "Jan 2026",
        date: "January 26",
        emoji: "🌴",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 89,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: bulbous base, curly leaf fronds.",
      },
      {
        id: "pp-2",
        month: "Mar 2026",
        date: "March 28",
        emoji: "🌴",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 94,
        change: "improved",
        headline: "New fronds",
        detail: "Fresh curled fronds emerging from the crown.",
      },
    ],
  },
  {
    id: "succulents-mix",
    name: "Succulent Mix",
    scientific: "Echeveria sp.",
    emoji: "🌵",
    photo: "/plants/succulents-mix.svg",
    gradient: "bg-[oklch(0.85_0.06_20)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 91,
    origin: "Mexico",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Rosette-forming succulents that come in vibrant colors and bloom with delicate flowers.",
    lastWatered: "10 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "em-1",
        month: "Feb 2026",
        date: "February 1",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 87,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: multiple rosettes, compact growth.",
      },
      {
        id: "em-2",
        month: "Mar 2026",
        date: "March 5",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 91,
        change: "improved",
        headline: "Color deepening",
        detail: "Rosettes displaying deeper hues with increased light exposure.",
      },
    ],
  },
  {
    id: "philodendron-pink-princess",
    name: "Philodendron Pink Princess",
    scientific: "Philodendron erubescens",
    emoji: "💚",
    photo: "/plants/philodendron-pink-princess.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 85,
    origin: "Central America",
    toxicity: "Toxic to pets",
    water: "Weekly, let top inch dry.",
    sunlight: "Bright, indirect light for pink variegation.",
    soil: "Well-draining aroid mix.",
    fact: "Highly sought after for its pink variegated leaves that deepen with maturity.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pp-1",
        month: "Feb 2026",
        date: "February 20",
        emoji: "💚",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 78,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: young plant with minimal pink variegation.",
      },
      {
        id: "pp-2",
        month: "Mar 2026",
        date: "March 25",
        emoji: "💚",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 85,
        change: "improved",
        headline: "Pink variegation emerging",
        detail: "New leaves showing pink highlights as plant matures.",
      },
    ],
  },
  {
    id: "alocasia-polly",
    name: "Alocasia Polly",
    scientific: "Alocasia × amazonica",
    emoji: "🗡️",
    photo: "/plants/alocasia-polly.jpg",
    gradient: "bg-[oklch(0.58_0.1_155)]",
    tone: "text-[oklch(0.42_0.09_15)]",
    status: "healthy",
    health: 82,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, keep soil moist but not wet.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Dramatic arrow-shaped leaves with white veining make it a striking houseplant.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ap-1",
        month: "Feb 2026",
        date: "February 10",
        emoji: "🗡️",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 75,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: 4 mature leaves with prominent veining.",
      },
      {
        id: "ap-2",
        month: "Mar 2026",
        date: "March 18",
        emoji: "🗡️",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 82,
        change: "improved",
        headline: "New leaf unfurling",
        detail: "Fresh arrow-shaped leaf emerging with strong vein contrast.",
      },
    ],
  },
  {
    id: "epipremnum-pinnatum",
    name: "Epipremnum Pinnatum",
    scientific: "Epipremnum pinnatum",
    emoji: "🌿",
    photo: "/plants/epipremnum-pinnatum.svg",
    gradient: "bg-[oklch(0.78_0.13_95)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 88,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, when top inch is dry.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining aroid mix.",
    fact: "Similar to Pothos but develops larger, deeply fenestrated leaves as it matures.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ep-1",
        month: "Jan 2026",
        date: "January 15",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 82,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: juvenile form with solid leaves.",
      },
      {
        id: "ep-2",
        month: "Mar 2026",
        date: "March 20",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 88,
        change: "improved",
        headline: "Fenestration beginning",
        detail: "First splits appearing on new leaves as plant matures.",
      },
    ],
  },
  {
    id: "syngonium-podophyllum",
    name: "Syngonium Podophyllum",
    scientific: "Syngonium podophyllum",
    emoji: "🌿",
    photo: "/plants/syngonium-podophyllum.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 84,
    origin: "Central America",
    toxicity: "Toxic to pets",
    water: "Weekly, keep lightly moist.",
    sunlight: "Medium to bright indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Arrow-shaped leaves that develop lobes as the plant matures.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sp-1",
        month: "Feb 2026",
        date: "February 8",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 78,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: young arrow-shaped foliage.",
      },
      {
        id: "sp-2",
        month: "Mar 2026",
        date: "March 22",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 84,
        change: "improved",
        headline: "Lobes developing",
        detail: "Leaf shape evolving with age, showing natural maturation.",
      },
    ],
  },
  {
    id: "scindapsus-pictus",
    name: "Scindapsus Pictus",
    scientific: "Scindapsus pictus",
    emoji: "🌿",
    photo: "/plants/scindapsus-pictus.svg",
    gradient: "bg-[oklch(0.72_0.11_35)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 80,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Every 10 days, let soil dry between waterings.",
    sunlight: "Medium, indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Satin Pothos features silver-spotted leaves on trailing vines.",
    lastWatered: "6 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sp-1",
        month: "Feb 2026",
        date: "February 14",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 75,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: compact vine, distinct silver spots.",
      },
      {
        id: "sp-2",
        month: "Mar 2026",
        date: "March 21",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 80,
        change: "improved",
        headline: "Vine extending",
        detail: "Trailing growth with new spotted leaves.",
      },
    ],
  },
  {
    id: "rhaphidophora-tetrasperma",
    name: "Mini Monstera",
    scientific: "Rhaphidophora tetrasperma",
    emoji: "🍃",
    photo: "/plants/rhaphidophora-tetrasperma.jpg",
    gradient: "bg-[oklch(0.62_0.12_145)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 86,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, keep soil evenly moist.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining aroid mix.",
    fact: "Compact version of Monstera with pre-split juvenile leaves.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "rm-1",
        month: "Feb 2026",
        date: "February 12",
        emoji: "🍃",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: compact plant with split leaves.",
      },
      {
        id: "rm-2",
        month: "Mar 2026",
        date: "March 19",
        emoji: "🍃",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 86,
        change: "improved",
        headline: "New growth emerging",
        detail: "Fresh leaves with naturally split form.",
      },
    ],
  },
  {
    id: "maranta-red-prayer-plant",
    name: "Red Prayer Plant",
    scientific: "Maranta leuconeura 'Red'",
    emoji: "🌿",
    photo: "/plants/maranta-red-prayer-plant.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 77,
    origin: "Brazil",
    toxicity: "Pet safe",
    water: "Keep soil evenly moist.",
    sunlight: "Medium, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Distinctive red veins and fold leaves upright at night.",
    lastWatered: "2 days ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "rp-1",
        month: "Feb 2026",
        date: "February 16",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 71,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: vibrant red veining on leaves.",
      },
      {
        id: "rp-2",
        month: "Mar 2026",
        date: "March 23",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 77,
        change: "improved",
        headline: "Veins deepening",
        detail: "Red coloration intensifying with consistent care.",
      },
    ],
  },
  {
    id: "ctenanthe-burle-marx",
    name: "Ctenanthe Burle Marx",
    scientific: "Ctenanthe setosa",
    emoji: "🌿",
    photo: "/plants/ctenanthe-burle-marx.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 78,
    origin: "Brazil",
    toxicity: "Pet safe",
    water: "Keep soil evenly moist.",
    sunlight: "Medium, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Striking large leaves with silvery patterns and burgundy undersides.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "cb-1",
        month: "Feb 2026",
        date: "February 11",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 72,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: large patterned leaves with red undersides.",
      },
      {
        id: "cb-2",
        month: "Mar 2026",
        date: "March 17",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 78,
        change: "improved",
        headline: "New leaf unfolding",
        detail: "Fresh foliage maintaining striking pattern.",
      },
    ],
  },
  {
    id: "stromanthe-triostar",
    name: "Stromanthe Triostar",
    scientific: "Stromanthe sanguinea",
    emoji: "🌿",
    photo: "/plants/stromanthe-triostar.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 76,
    origin: "Brazil",
    toxicity: "Pet safe",
    water: "Keep soil evenly moist.",
    sunlight: "Bright, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Tricolored leaves with red, white, and green patterns.",
    lastWatered: "1 day ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "st-1",
        month: "Feb 2026",
        date: "February 9",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 70,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: vivid tricolored variegation.",
      },
      {
        id: "st-2",
        month: "Mar 2026",
        date: "March 16",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 76,
        change: "improved",
        headline: "Colors brightening",
        detail: "Pattern intensity increasing with proper lighting.",
      },
    ],
  },
  {
    id: "anthurium-clarinervium",
    name: "Anthurium Clarinervium",
    scientific: "Anthurium clarinervium",
    emoji: "❤️",
    photo: "/plants/anthurium-clarinervium.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 81,
    origin: "Colombia",
    toxicity: "Toxic to pets",
    water: "Weekly, let top inch dry.",
    sunlight: "Bright, indirect light.",
    soil: "Chunky, well-draining aroid mix.",
    fact: "Dark velvety leaves with striking white vein patterns.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ac-1",
        month: "Feb 2026",
        date: "February 13",
        emoji: "❤️",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 75,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: velvety dark foliage with white veining.",
      },
      {
        id: "ac-2",
        month: "Mar 2026",
        date: "March 21",
        emoji: "❤️",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 81,
        change: "improved",
        headline: "Leaf size increasing",
        detail: "New leaves displaying stronger vein contrast.",
      },
    ],
  },
  {
    id: "homalomena-rubescens",
    name: "Red Shield Plant",
    scientific: "Homalomena rubescens",
    emoji: "🛡️",
    photo: "/plants/homalomena-rubescens.jpg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 79,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, keep soil lightly moist.",
    sunlight: "Medium to bright indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Deep red foliage on compact plant with compact growth habit.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "rs-1",
        month: "Feb 2026",
        date: "February 18",
        emoji: "🛡️",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 73,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: deep red compact foliage.",
      },
      {
        id: "rs-2",
        month: "Mar 2026",
        date: "March 24",
        emoji: "🛡️",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 79,
        change: "improved",
        headline: "Color deepening",
        detail: "Red hues intensifying with maturity.",
      },
    ],
  },
  {
    id: "dischidia-rafflesiana",
    name: "Lipstick Plant",
    scientific: "Aeschynanthus radicans",
    emoji: "💋",
    photo: "/plants/dischidia-rafflesiana.svg",
    gradient: "bg-[oklch(0.85_0.06_20)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 83,
    origin: "Southeast Asia",
    toxicity: "Pet safe",
    water: "Keep soil moist, not soggy.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Produces vibrant red-orange flowers resembling lipstick.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "lp-1",
        month: "Feb 2026",
        date: "February 20",
        emoji: "💋",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 77,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: trailing vines with glossy leaves.",
      },
      {
        id: "lp-2",
        month: "Mar 2026",
        date: "March 26",
        emoji: "💋",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 83,
        change: "improved",
        headline: "Buds forming",
        detail: "Red flower buds appearing at stem tips.",
      },
    ],
  },
  {
    id: "pinguicula",
    name: "Butterwort",
    scientific: "Pinguicula moranensis",
    emoji: "🌿",
    photo: "/plants/pinguicula.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 74,
    origin: "Mexico",
    toxicity: "Pet safe",
    water: "Keep soil moist using distilled water.",
    sunlight: "Bright, indirect light.",
    soil: "Carnivorous plant mix.",
    fact: "Carnivorous plant that traps insects on sticky leaves.",
    lastWatered: "2 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "bu-1",
        month: "Feb 2026",
        date: "February 21",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 68,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: sticky rosette leaves.",
      },
      {
        id: "bu-2",
        month: "Mar 2026",
        date: "March 27",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 74,
        change: "improved",
        headline: "Flower spike emerging",
        detail: "Purple flowers developing at center.",
      },
    ],
  },
  {
    id: "nepenthes-ventrata",
    name: "Monkey Cup Plant",
    scientific: "Nepenthes × ventrata",
    emoji: "🪤",
    photo: "/plants/nepenthes-ventrata.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 72,
    origin: "Southeast Asia",
    toxicity: "Pet safe",
    water: "Keep soil moist, high humidity required.",
    sunlight: "Bright, indirect light.",
    soil: "Bark and sphagnum moss mix.",
    fact: "Carnivorous plant with tubular pitcher traps for insects.",
    lastWatered: "1 day ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "mc-1",
        month: "Feb 2026",
        date: "February 22",
        emoji: "🪤",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 65,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: developing pitcher traps.",
      },
      {
        id: "mc-2",
        month: "Mar 2026",
        date: "March 28",
        emoji: "🪤",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 72,
        change: "improved",
        headline: "New pitchers forming",
        detail: "Additional traps developing with consistent humidity.",
      },
    ],
  },
  {
    id: "sarracenia-purpurea",
    name: "Pitcher Plant",
    scientific: "Sarracenia purpurea",
    emoji: "🪤",
    photo: "/plants/sarracenia-purpurea.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 70,
    origin: "North America",
    toxicity: "Pet safe",
    water: "Keep moist with rainwater, dormancy required.",
    sunlight: "Bright, indirect light.",
    soil: "Peat and sand mix.",
    fact: "Hardy carnivorous pitcher plant with reddish pitchers.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pp-1",
        month: "Jan 2026",
        date: "January 20",
        emoji: "🪤",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 65,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: dormant period, compact growth.",
      },
      {
        id: "pp-2",
        month: "Mar 2026",
        date: "March 15",
        emoji: "🪤",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 70,
        change: "improved",
        headline: "Spring growth resuming",
        detail: "New pitchers emerging as dormancy ends.",
      },
    ],
  },
  {
    id: "dionaea-muscipula",
    name: "Venus Flytrap",
    scientific: "Dionaea muscipula",
    emoji: "🫀",
    photo: "/plants/dionaea-muscipula.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 68,
    origin: "North Carolina",
    toxicity: "Pet safe",
    water: "Keep moist with rainwater, dormancy period required.",
    sunlight: "Very bright, 12+ hours needed.",
    soil: "Peat and sand mix.",
    fact: "Carnivorous plant that closes its trap jaws when prey touches trigger hairs.",
    lastWatered: "2 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "vf-1",
        month: "Jan 2026",
        date: "January 5",
        emoji: "🫀",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 62,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: red-tinged trap leaves.",
      },
      {
        id: "vf-2",
        month: "Mar 2026",
        date: "March 10",
        emoji: "🫀",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 68,
        change: "improved",
        headline: "Color intensifying",
        detail: "Red pigmentation deepening with spring light.",
      },
    ],
  },
  {
    id: "rex-begonia-escargot",
    name: "Escargot Begonia",
    scientific: "Begonia rex 'Escargot'",
    emoji: "🍁",
    photo: "/plants/rex-begonia-escargot.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.35_0.05_140)]",
    status: "healthy",
    health: 75,
    origin: "Hybrid cultivar",
    toxicity: "Toxic to pets",
    water: "Weekly, avoid wetting leaves.",
    sunlight: "Medium, indirect light.",
    soil: "Light, well-draining potting mix.",
    fact: "Leaves spiral in a snail-shell pattern with metallic silver markings.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "eb-1",
        month: "Feb 2026",
        date: "February 15",
        emoji: "🍁",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 69,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: distinctive spiral leaf pattern.",
      },
      {
        id: "eb-2",
        month: "Mar 2026",
        date: "March 22",
        emoji: "🍁",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 75,
        change: "improved",
        headline: "New spiral leaves",
        detail: "Metallic sheen becoming more pronounced.",
      },
    ],
  },
  {
    id: "fittonia-white",
    name: "White Nerve Plant",
    scientific: "Fittonia albivenis",
    emoji: "🌿",
    photo: "/plants/fittonia-white.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 73,
    origin: "Peru",
    toxicity: "Pet safe",
    water: "Keep soil consistently moist.",
    sunlight: "Medium, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Delicate leaves with intricate white vein patterns.",
    lastWatered: "1 day ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "fn-1",
        month: "Feb 2026",
        date: "February 17",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 67,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: intricate white-veined leaves.",
      },
      {
        id: "fn-2",
        month: "Mar 2026",
        date: "March 25",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 73,
        change: "improved",
        headline: "Leaf veins brightening",
        detail: "White patterns becoming more vivid.",
      },
    ],
  },
  {
    id: "fittonia-red",
    name: "Red Nerve Plant",
    scientific: "Fittonia argyroneura",
    emoji: "🌿",
    photo: "/plants/fittonia-red.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 72,
    origin: "Peru",
    toxicity: "Pet safe",
    water: "Keep soil consistently moist.",
    sunlight: "Medium, indirect light.",
    soil: "Peat-based, moisture-retentive mix.",
    fact: "Companion to white nerve plant with red vein patterns.",
    lastWatered: "1 day ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "fr-1",
        month: "Feb 2026",
        date: "February 19",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 66,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: delicate red-veined foliage.",
      },
      {
        id: "fr-2",
        month: "Mar 2026",
        date: "March 26",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 72,
        change: "improved",
        headline: "Red veining intensifying",
        detail: "Colors deepening with stable humidity.",
      },
    ],
  },
  {
    id: "tradescantia-zebrina",
    name: "Wandering Dude",
    scientific: "Tradescantia zebrina",
    emoji: "🌿",
    photo: "/plants/tradescantia-zebrina.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 87,
    origin: "Mexico",
    toxicity: "Toxic to pets",
    water: "Weekly, let soil dry between waterings.",
    sunlight: "Bright, indirect to direct light.",
    soil: "Standard well-draining potting mix.",
    fact: "Trailing plant with purple undersides and green-silver tops on leaves.",
    lastWatered: "5 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "tz-1",
        month: "Jan 2026",
        date: "January 28",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 81,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: trailing vines with purple undersides.",
      },
      {
        id: "tz-2",
        month: "Mar 2026",
        date: "March 30",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 87,
        change: "improved",
        headline: "Vines extending",
        detail: "Purple coloration intensifying with bright light.",
      },
    ],
  },
  {
    id: "tradescantia-nanouk",
    name: "Tradescantia Nanouk",
    scientific: "Tradescantia 'Nanouk'",
    emoji: "🌿",
    photo: "/plants/tradescantia-nanouk.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.45_0.09_75)]",
    status: "healthy",
    health: 85,
    origin: "Hybrid cultivar",
    toxicity: "Toxic to pets",
    water: "Weekly, let soil dry between waterings.",
    sunlight: "Bright, indirect to direct light.",
    soil: "Standard well-draining potting mix.",
    fact: "Compact trailing plant with pink, purple, and white variegated foliage.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "tn-1",
        month: "Feb 2026",
        date: "February 3",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 79,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: colorful tricolored compact growth.",
      },
      {
        id: "tn-2",
        month: "Mar 2026",
        date: "March 29",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 85,
        change: "improved",
        headline: "Colors vibrant",
        detail: "Pink and purple hues deepening significantly.",
      },
    ],
  },
  {
    id: "hoya-carnosa",
    name: "Wax Plant",
    scientific: "Hoya carnosa",
    emoji: "🌸",
    photo: "/plants/hoya-carnosa.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 89,
    origin: "East Asia",
    toxicity: "Pet safe",
    water: "Every 2 weeks, drought tolerant.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Waxy star-shaped flowers that emit sweet fragrance and produce sugary nectar.",
    lastWatered: "8 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "hc-1",
        month: "Jan 2026",
        date: "January 12",
        emoji: "🌸",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 84,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: mature vines with glossy leaves.",
      },
      {
        id: "hc-2",
        month: "Mar 2026",
        date: "March 11",
        emoji: "🌸",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 89,
        change: "improved",
        headline: "Flower buds forming",
        detail: "Star clusters developing — fragrant bloom incoming.",
      },
    ],
  },
  {
    id: "hoya-pubicalyx",
    name: "Hoya Pubicalyx",
    scientific: "Hoya pubicalyx",
    emoji: "🌸",
    photo: "/plants/hoya-pubicalyx.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 86,
    origin: "Philippines",
    toxicity: "Pet safe",
    water: "Every 2 weeks, drought tolerant.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Dark burgundy-edged leaves with fragrant pink flower clusters.",
    lastWatered: "7 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "hp-1",
        month: "Feb 2026",
        date: "February 2",
        emoji: "🌸",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: deep burgundy-edged foliage.",
      },
      {
        id: "hp-2",
        month: "Mar 2026",
        date: "March 14",
        emoji: "🌸",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 86,
        change: "improved",
        headline: "Buds forming",
        detail: "Pink flower clusters developing at leaf axils.",
      },
    ],
  },
  {
    id: "senecio-rowleyanus-string-of-pearls-variegated",
    name: "Variegated String of Pearls",
    scientific: "Senecio rowleyanus var.",
    emoji: "📿",
    photo: "/plants/senecio-rowleyanus-string-of-pearls-variegated.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 77,
    origin: "Southwest Africa",
    toxicity: "Toxic to pets",
    water: "Every 2 weeks. Very drought tolerant.",
    sunlight: "Bright, indirect to direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Variegated version with cream and green beaded leaves.",
    lastWatered: "10 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sv-1",
        month: "Feb 2026",
        date: "February 23",
        emoji: "📿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 72,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: variegated cream and green strands.",
      },
      {
        id: "sv-2",
        month: "Mar 2026",
        date: "March 24",
        emoji: "📿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 77,
        change: "improved",
        headline: "New strands trailing",
        detail: "Variegation remaining strong with growth.",
      },
    ],
  },
  {
    id: "echeveria-black-prince",
    name: "Black Prince Echeveria",
    scientific: "Echeveria 'Black Prince'",
    emoji: "🌵",
    photo: "/plants/echeveria-black-prince.svg",
    gradient: "bg-[oklch(0.85_0.06_20)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 88,
    origin: "Mexico",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Nearly black rosettes that blush red in bright light.",
    lastWatered: "11 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "bp-1",
        month: "Feb 2026",
        date: "February 8",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 83,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: dark purple-black rosette.",
      },
      {
        id: "bp-2",
        month: "Mar 2026",
        date: "March 5",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 88,
        change: "improved",
        headline: "Red blushing",
        detail: "Edges developing crimson hues in bright light.",
      },
    ],
  },
  {
    id: "sempervivum-arachnoideum",
    name: "Cobweb Houseleek",
    scientific: "Sempervivum arachnoideum",
    emoji: "🌵",
    photo: "/plants/sempervivum-arachnoideum.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 93,
    origin: "European Alps",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Extremely drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining gritty succulent mix.",
    fact: "Rosette covered in fine webbing that resembles a spider's web.",
    lastWatered: "15 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sh-1",
        month: "Jan 2026",
        date: "January 10",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 90,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: rosette with cobweb-like hairs.",
      },
      {
        id: "sh-2",
        month: "Mar 2026",
        date: "March 2",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 93,
        change: "stable",
        headline: "Thriving with minimal care",
        detail: "Webbing intact, compact form maintained.",
      },
    ],
  },
  {
    id: "aeonium-arboreum",
    name: "Aeonium Tree",
    scientific: "Aeonium arboreum",
    emoji: "🌳",
    photo: "/plants/aeonium-arboreum.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 85,
    origin: "Canary Islands",
    toxicity: "Pet safe",
    water: "Every 2 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Tree-like succulent with geometric rosette flowers.",
    lastWatered: "9 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ae-1",
        month: "Feb 2026",
        date: "February 4",
        emoji: "🌳",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: multiple rosettes on stems.",
      },
      {
        id: "ae-2",
        month: "Mar 2026",
        date: "March 9",
        emoji: "🌳",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 85,
        change: "improved",
        headline: "Rosettes enlarging",
        detail: "Main rosette growing, color deepening.",
      },
    ],
  },
  {
    id: "graptopetalum-paraguayense",
    name: "Ghost Plant",
    scientific: "Graptopetalum paraguayense",
    emoji: "👻",
    photo: "/plants/graptopetalum-paraguayense.svg",
    gradient: "bg-[oklch(0.88_0.04_50)]",
    tone: "text-[oklch(0.42_0.08_40)]",
    status: "healthy",
    health: 89,
    origin: "Mexico",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Pale whitish-pink rosettes that can turn lavender in cool weather.",
    lastWatered: "12 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "gp-1",
        month: "Feb 2026",
        date: "February 5",
        emoji: "👻",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 84,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: pale pink-white rosettes.",
      },
      {
        id: "gp-2",
        month: "Mar 2026",
        date: "March 6",
        emoji: "👻",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 89,
        change: "improved",
        headline: "Color developing",
        detail: "Lavender tones appearing with temperature shifts.",
      },
    ],
  },
  {
    id: "crassula-ovata-variegata",
    name: "Variegated Jade Plant",
    scientific: "Crassula ovata 'Variegata'",
    emoji: "🍀",
    photo: "/plants/crassula-ovata-variegata.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 92,
    origin: "South Africa",
    toxicity: "Toxic to pets",
    water: "Every 2–3 weeks. Drought tolerant.",
    sunlight: "Bright, direct to indirect light.",
    soil: "Fast-draining succulent mix.",
    fact: "Variegated form with cream and green leaves, occasional red margins.",
    lastWatered: "10 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "jv-1",
        month: "Jan 2026",
        date: "January 17",
        emoji: "🍀",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 88,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: cream-edged jade leaves.",
      },
      {
        id: "jv-2",
        month: "Mar 2026",
        date: "March 7",
        emoji: "🍀",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 92,
        change: "improved",
        headline: "Variegation vibrant",
        detail: "Cream edges crisp, red margins intensifying.",
      },
    ],
  },
  {
    id: "sedum-rupestre",
    name: "Reflexed Stonecrop",
    scientific: "Sedum rupestre",
    emoji: "🌵",
    photo: "/plants/sedum-rupestre.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 90,
    origin: "Mediterranean",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining succulent mix.",
    fact: "Trailing stonecrop with tiny blue-green leaves that turn orange in cold.",
    lastWatered: "14 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "rs-1",
        month: "Feb 2026",
        date: "February 6",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 85,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: trailing blue-green stems.",
      },
      {
        id: "rs-2",
        month: "Mar 2026",
        date: "March 8",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 90,
        change: "improved",
        headline: "Color shifting",
        detail: "Orange tones appearing with cool spring nights.",
      },
    ],
  },
  {
    id: "euphorbia-pulcherrima",
    name: "Poinsettia",
    scientific: "Euphorbia pulcherrima",
    emoji: "🌹",
    photo: "/plants/euphorbia-pulcherrima.svg",
    gradient: "bg-[oklch(0.85_0.06_20)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 78,
    origin: "Mexico",
    toxicity: "Mildly toxic",
    water: "Keep soil moist during blooming season.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining potting mix.",
    fact: "Red bracts are modified leaves; true flowers are small yellow structures.",
    lastWatered: "2 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ps-1",
        month: "Dec 2025",
        date: "December 1",
        emoji: "🌹",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 85,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: vibrant red bracts at full bloom.",
      },
      {
        id: "ps-2",
        month: "Mar 2026",
        date: "March 30",
        emoji: "🌹",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 78,
        change: "declined",
        headline: "Post-bloom decline",
        detail: "Bracts fading — normal after holiday season.",
      },
    ],
  },
  {
    id: "schlumbergera-truncata",
    name: "Easter Cactus",
    scientific: "Hatiora gaertneri",
    emoji: "🌸",
    photo: "/plants/schlumbergera-truncata.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 86,
    origin: "Brazil",
    toxicity: "Pet safe",
    water: "Weekly, keep lightly moist during growth.",
    sunlight: "Bright, indirect light.",
    soil: "Well-draining potting mix with added organic matter.",
    fact: "Tropical cactus blooming in spring with pink-red flowers.",
    lastWatered: "4 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ec-1",
        month: "Feb 2026",
        date: "February 14",
        emoji: "🌸",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 80,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: segmented stems, buds appearing.",
      },
      {
        id: "ec-2",
        month: "Mar 2026",
        date: "March 20",
        emoji: "🌸",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 86,
        change: "improved",
        headline: "Blooming",
        detail: "Pink flowers opening along stem segments.",
      },
    ],
  },
  {
    id: "mammillaria-bombycina",
    name: "Silk Pincushion Cactus",
    scientific: "Mammillaria bombycina",
    emoji: "🌵",
    photo: "/plants/mammillaria-bombycina.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 84,
    origin: "Mexico",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining cactus mix.",
    fact: "Small round cactus covered in soft silky spines with pink flowers.",
    lastWatered: "13 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "sp-1",
        month: "Feb 2026",
        date: "February 11",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 79,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: compact round form with silky spines.",
      },
      {
        id: "sp-2",
        month: "Mar 2026",
        date: "March 14",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 84,
        change: "improved",
        headline: "Buds forming",
        detail: "Pink flower buds appearing around crown.",
      },
    ],
  },
  {
    id: "cereus-repandus",
    name: "Peruvian Apple Cactus",
    scientific: "Cereus repandus",
    emoji: "🌵",
    photo: "/plants/cereus-repandus.svg",
    gradient: "bg-[oklch(0.86_0.05_45)]",
    tone: "text-[oklch(0.38_0.04_55)]",
    status: "healthy",
    health: 87,
    origin: "South America",
    toxicity: "Pet safe",
    water: "Every 3 weeks. Drought tolerant.",
    sunlight: "Bright, direct light.",
    soil: "Fast-draining cactus mix.",
    fact: "Tall columnar cactus that produces edible pink fruits.",
    lastWatered: "15 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "pav-1",
        month: "Jan 2026",
        date: "January 8",
        emoji: "🌵",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 84,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: columnar green stem segments.",
      },
      {
        id: "pav-2",
        month: "Mar 2026",
        date: "March 12",
        emoji: "🌵",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 87,
        change: "improved",
        headline: "Growth extending",
        detail: "New segments forming at crown.",
      },
    ],
  },
  {
    id: "polyscias-guilfoylei",
    name: "Polyscias",
    scientific: "Polyscias guilfoylei",
    emoji: "🌿",
    photo: "/plants/polyscias-guilfoylei.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 71,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Keep soil consistently moist.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Delicate feathery variegated foliage on tree-like structure.",
    lastWatered: "2 days ago",
    nextTask: "Mist today",
    timeline: [
      {
        id: "pol-1",
        month: "Feb 2026",
        date: "February 20",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.04_50)]",
        health: 65,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: delicate variegated foliage.",
      },
      {
        id: "pol-2",
        month: "Mar 2026",
        date: "March 27",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 71,
        change: "improved",
        headline: "Stabilized with care",
        detail: "Leaf drop halted with consistent watering.",
      },
    ],
  },
  {
    id: "excoecaria-pulchella",
    name: "Excoecaria",
    scientific: "Excoecaria pulchella",
    emoji: "🌿",
    photo: "/plants/excoecaria-pulchella.svg",
    gradient: "bg-[oklch(0.85_0.05_140)]",
    tone: "text-[oklch(0.4_0.09_35)]",
    status: "healthy",
    health: 73,
    origin: "Southeast Asia",
    toxicity: "Toxic to pets",
    water: "Weekly, keep lightly moist.",
    sunlight: "Bright, indirect light.",
    soil: "Rich, well-draining potting mix.",
    fact: "Red and pink variegated compact foliage.",
    lastWatered: "3 days ago",
    nextTask: "Nothing today",
    timeline: [
      {
        id: "ex-1",
        month: "Feb 2026",
        date: "February 18",
        emoji: "🌿",

        gradient: "bg-[oklch(0.88_0.06_85)]",
        health: 67,
        change: "new",
        headline: "Added to your garden",
        detail: "Baseline: red-tinged compact growth.",
      },
      {
        id: "ex-2",
        month: "Mar 2026",
        date: "March 25",
        emoji: "🌿",

        gradient: "bg-[oklch(0.87_0.04_20)]",
        health: 73,
        change: "improved",
        headline: "Colors deepening",
        detail: "Pink and red variegation becoming more vivid.",
      },
    ],
  },
];

export const todaysTasks = [
  { id: "t1", plantId: "monstera", label: "Water Monstera", kind: "Water" as const },
  { id: "t2", plantId: "pothos", label: "Mist Golden Pothos", kind: "Mist" as const },
  { id: "t3", plantId: "fiddle", label: "Rotate Fiddle Leaf Fig", kind: "Care" as const },
  { id: "t4", plantId: "calathea", label: "Inspect Calathea for pests", kind: "Check" as const },
];

export const statusLabel: Record<PlantStatus, string> = {
  "needs-water": "Needs water today",
  healthy: "Healthy",
  quarantined: "Quarantined",
  "needs-mist": "Mist today",
};

export const statusTone: Record<PlantStatus, string> = {
  "needs-water": "border-border text-foreground",
  healthy: "border-border text-muted-foreground",
  quarantined: "border-[oklch(0.5_0.13_35)] text-[oklch(0.4_0.09_35)]",
  "needs-mist": "border-border text-foreground",
};

// Import the new 1000-plant catalog
import { expandedCatalogPlants, TOTAL_PLANTS as CATALOG_SIZE } from "./plants-catalog-1000";

// Combine all demo plants (original 5) and catalog plants into one array
export const plants: Plant[] = [...allDemoPlants, ...catalogPlants];

// Keep speciesCatalog for backward compatibility
export const speciesCatalog: Plant[] = catalogPlants;

// New expanded catalog with 1000 plants
export const expandedSpeciesCatalog: Plant[] = expandedCatalogPlants;

export const TOTAL_PLANTS_IN_CATALOG = CATALOG_SIZE;

export function getPlant(id: string) {
  return (
    plants.find((p) => p.id === id) ??
    expandedSpeciesCatalog.find((p) => p.id === id) ??
    speciesCatalog.find((p) => p.id === id)
  );
}
