[build]
  command = "npm run build"
  publish = "dist"
  node_version = "24.13.1"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = "dist"
