/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExplorerRouteImport } from './routes/api-explorer'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlantIdRouteImport } from './routes/plant.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplorerRoute = ApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIdRoute = PlantIdRouteImport.update({
  id: '/plant/$id',
  path: '/plant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/doctor': typeof DoctorRoute
  '/explore': typeof ExploreRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/plant/$id': typeof PlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/doctor': typeof DoctorRoute
  '/explore': typeof ExploreRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/plant/$id': typeof PlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/doctor': typeof DoctorRoute
  '/explore': typeof ExploreRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/plant/$id': typeof PlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-explorer'
    | '/doctor'
    | '/explore'
    | '/scan'
    | '/settings'
    | '/plant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-explorer'
    | '/doctor'
    | '/explore'
    | '/scan'
    | '/settings'
    | '/plant/$id'
  id:
    | '__root__'
    | '/'
    | '/api-explorer'
    | '/doctor'
    | '/explore'
    | '/scan'
    | '/settings'
    | '/plant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExplorerRoute: typeof ApiExplorerRoute
  DoctorRoute: typeof DoctorRoute
  ExploreRoute: typeof ExploreRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  PlantIdRoute: typeof PlantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-explorer': {
      id: '/api-explorer'
      path: '/api-explorer'
      fullPath: '/api-explorer'
      preLoaderRoute: typeof ApiExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/$id': {
      id: '/plant/$id'
      path: '/plant/$id'
      fullPath: '/plant/$id'
      preLoaderRoute: typeof PlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExplorerRoute: ApiExplorerRoute,
  DoctorRoute: DoctorRoute,
  ExploreRoute: ExploreRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  PlantIdRoute: PlantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
