/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskExpertRouteImport } from './routes/ask-expert'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiSensorIngestRouteImport } from './routes/api.sensor-ingest'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as PlantIdRouteImport } from './routes/plant.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskExpertRoute = AskExpertRouteImport.update({
  id: '/ask-expert',
  path: '/ask-expert',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSensorIngestRoute = ApiSensorIngestRouteImport.update({
  id: '/api/sensor-ingest',
  path: '/api/sensor-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantIdRoute = PlantIdRouteImport.update({
  id: '/plant/$id',
  path: '/plant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-expert': typeof AskExpertRoute
  '/doctor': typeof DoctorRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/streak': typeof StreakRoute
  '/terms': typeof TermsRoute
  '/api/sensor-ingest': typeof ApiSensorIngestRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/plant/$id': typeof PlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-expert': typeof AskExpertRoute
  '/doctor': typeof DoctorRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/streak': typeof StreakRoute
  '/terms': typeof TermsRoute
  '/api/sensor-ingest': typeof ApiSensorIngestRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/plant/$id': typeof PlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-expert': typeof AskExpertRoute
  '/doctor': typeof DoctorRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/streak': typeof StreakRoute
  '/terms': typeof TermsRoute
  '/api/sensor-ingest': typeof ApiSensorIngestRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/plant/$id': typeof PlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-expert'
    | '/doctor'
    | '/explore'
    | '/login'
    | '/premium'
    | '/privacy'
    | '/reset-password'
    | '/scan'
    | '/sensors'
    | '/settings'
    | '/signup'
    | '/streak'
    | '/terms'
    | '/api/sensor-ingest'
    | '/api/stripe-webhook'
    | '/plant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-expert'
    | '/doctor'
    | '/explore'
    | '/login'
    | '/premium'
    | '/privacy'
    | '/reset-password'
    | '/scan'
    | '/sensors'
    | '/settings'
    | '/signup'
    | '/streak'
    | '/terms'
    | '/api/sensor-ingest'
    | '/api/stripe-webhook'
    | '/plant/$id'
  id:
    | '__root__'
    | '/'
    | '/ask-expert'
    | '/doctor'
    | '/explore'
    | '/login'
    | '/premium'
    | '/privacy'
    | '/reset-password'
    | '/scan'
    | '/sensors'
    | '/settings'
    | '/signup'
    | '/streak'
    | '/terms'
    | '/api/sensor-ingest'
    | '/api/stripe-webhook'
    | '/plant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskExpertRoute: typeof AskExpertRoute
  DoctorRoute: typeof DoctorRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StreakRoute: typeof StreakRoute
  TermsRoute: typeof TermsRoute
  ApiSensorIngestRoute: typeof ApiSensorIngestRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  PlantIdRoute: typeof PlantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-expert': {
      id: '/ask-expert'
      path: '/ask-expert'
      fullPath: '/ask-expert'
      preLoaderRoute: typeof AskExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sensor-ingest': {
      id: '/api/sensor-ingest'
      path: '/api/sensor-ingest'
      fullPath: '/api/sensor-ingest'
      preLoaderRoute: typeof ApiSensorIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant/$id': {
      id: '/plant/$id'
      path: '/plant/$id'
      fullPath: '/plant/$id'
      preLoaderRoute: typeof PlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskExpertRoute: AskExpertRoute,
  DoctorRoute: DoctorRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StreakRoute: StreakRoute,
  TermsRoute: TermsRoute,
  ApiSensorIngestRoute: ApiSensorIngestRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  PlantIdRoute: PlantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
